[package]
name = "korr-ecs-bench"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bevy_ecs.workspace = true
hecs.workspace = true
korr-ecs.workspace = true
korr-random.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "ecs"
harness = false

[[bench]]
name = "presence"
harness = false

[lints]
workspace = true
